# Generated by Django 4.2.25 on 2025-11-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='status',
        ),
    ]
