# Generated by Django 4.2.25 on 2025-11-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='food_item',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='calories_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='carbohydrates_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='fats_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='protein_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
